<?php
/**
 * Zamoroka_Issuu
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to p@zamoroka.com so we can send you a copy immediately.
 *
 * @category  Issuu
 * @package   Zamoroka
 * @copyright Copyright (c) 2017 Zamoroka Pavlo (http://www.zamoroka.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var $this Zamoroka_Issuu_Block_View */
$issuuInfo = $this->getIssuuItem();
?>
<style>
    .issuuembed.issuu-isrendered {
        width: 100% !important;
    }
</style>
<h2><?php echo $issuuInfo->getTitle(); ?></h2>
<blockquote><?php echo $issuuInfo->getDescription(); ?></blockquote>
<div class="content"><?php echo $issuuInfo->getContent(); ?></div>
